### ISSUE TITLE
Decide where the dependent services will be hosted

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-widgets-wpf#10]
These addins have dependencies on non-public services:

Amazon Web Services:
Aircraft Communication Coverage Addin
Aircraft Route Generation Line Addin
Ground Communication Coverage Addin
Satellite Ephemeris Generation Addin

So just need to figure out where to host them, or otherwise document how to satisfy the dependency, in order to enable these addins to still work.

**Comment by jrweakland** [comment]
Added to backlog - https://app.asana.com/0/23186355169350/23186355169373

**Comment by jrweakland** [comment]
@jofraley informed me that we have already made this decision and they are hosted on an Amazon instance that @ACueva setup.
