### ISSUE TITLE
Compiler Warning: The result of the expression is always 'true'

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-widgets-wpf#20]
OOBWidgetDialog.xaml.cs:119
Compiler Warning: The result of the expression is always 'true' since a value of type 'OOB.DescriptionType' is never equal to 'null' of type 'OOB.DescriptionType?'

https://github.com/Esri/solutions-widgets-wpf/blob/master/source/OrderOfBattle/OrderOfBattle/Config/OOBWidgetDialog.xaml.cs#L119

**Comment by jrweakland** [comment]
Added to backlog - https://app.asana.com/0/23186355169350/23186355169366

**Comment by csmoore** [comment]
Looks fixed to me
