### ISSUE TITLE
Update this repo to build/test with Current and Next Version of Operations Dashboard+add prebuilt addins

### ISSUE THREAD

**Issue by jofraley** [Esri/solutions-widgets-wpf#23]
Primarily these widgets will be tested: 

- [ ] ERG
- [ ] Bomb Threat
- [ ] Find Closest Resource

CMoore Note:
Just an Implementation Note when we update the repos we now want to update them to work/build with the current and next versions of the products:

- [ ] Current Version (Currently 10.2.3 update 2?) – goes in master branch
- [ ]  Next Version (Currently 10.3?) – in “v.next” branch
- [ ]  Also - we've had some requests to include the pre-built addins in the application folder (so folks don't need to install VS20XX + Runtime SDK just to use/test) so please do that at the same time.

**Comment by jrweakland** [comment]
Added to backlog - https://app.asana.com/0/23186355169350/23186355169360

**Comment by csmoore** [comment]
Updated/edited the original description a bit - and a reminder we need to update this repo to the current (in master branch) and next version (in v.next branch) at the earliest convenience.

**Comment by joebayles** [comment]
@jofraley @csmoore I looked for these on the [National Security Portal](https://nsec.esri.com/arcgis/home/) and didn't see them. I tried building from the GitHub repository and ran into some Visual Studio issues. I then tried the widgets that are currently on the old [AFMIE Portal](https://afmiedev.esri.com/arcgis/home/), and the only ones I could get added to the dashboard were Order of Battle, and Range Fan (which didn't work properly, as far as I could tell). Please advise.

**Comment by csmoore** [comment]
This issue/task should probably be assigned to the stuckee responsible for fixing (probably @jofraley or @pHill5136)

**Comment by jofraley** [comment]
Updated all widgets to 10.2.3.  Also added all compiled addins to the application folder so that others can used the compiled versions.  @joebayles I am unable to upload the addins as items to the National Security Portal, I do not have permission.

**Comment by conklinbd** [comment]
@jofraley did you connect to https://nsec.esri.com/arcgis/home An account should have been automatically created. 
@pHill5136 or @joebayles can probably just upload these widgets but you might still want to make sure you have a working account for future

**Comment by jofraley** [comment]
@conklinbd yes I connected to that.  Avi took a look and even updated my role to Administrator and I still cannot add because it says I do not have permissions.  I think it has something to do with my setup here.

**Comment by conklinbd** [comment]
Weird. Ok. Someone else will have to do it.

**Comment by joebayles** [comment]
@jofraley should I be seeing something updated on the repo? The latest commit I see is from @pHill5136 on January 16th.

If all that is needed is to add the contents of the application folder to the portal, I can do that no problem. If I need to build it, I'll need some help troubleshooting my build errors.

**Comment by jofraley** [comment]
Looks like it only updated my repo.  I must have to do a pull request.

**Comment by joebayles** [comment]
Once https://github.com/Esri/solutions-widgets-wpf/pull/32 is merged I will finish this issue and close it out.

**Comment by ACueva** [comment]
I'm still working on this issue. https://github.com/Esri/ops-server-config/issues/734
@jofraley In the meantime if something needs to be uploaded please let me know and I can do it for you.

**Comment by joebayles** [comment]
@jofraley I'm pretty sure this issue can be closed out, since the work was already done and the access issue is a different one (https://github.com/Esri/ops-server-config/issues/734). Please let me know if it's not.
