### ISSUE TITLE
error : The Esri WPF SDK is not correctly installed - when built with {Next Version} - ex.10.2.4

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-widgets-wpf#29]
http://vjenk01.esri.com:8080/job/Daily%20Build-%20solutions-widgets-wpf/263/console

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 8/18/2014 9:30:39 PM.
Project "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AllSolutionsWidgets\AllSolutionsWidgets.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AllSolutionsWidgets\AllSolutionsWidgets.sln" (1) is building "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AircraftCommunicationCoverageAddin\AircraftCommunicationCoverageAddin\AircraftCommunicationCoverageAddin.csproj" (2) on node 1 (default targets).
C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AircraftCommunicationCoverageAddin\AircraftCommunicationCoverageAddin\AircraftCommunicationCoverageAddin.csproj(157,5): error : The Esri WPF SDK is not correctly installed - 'ESRI.ArcGIS.OperationsDashboard.targets' not found (IDEIntegrationFolder='').
Done Building Project "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AircraftCommunicationCoverageAddin\AircraftCommunicationCoverageAddin\AircraftCommunicationCoverageAddin.csproj" (default targets) -- FAILED.
Project "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AllSolutionsWidgets\AllSolutionsWidgets.sln" (1) is building "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AirCraftRouteGenerationLineAddin\AirCraftRouteGenerationLineAddin\AirCraftRouteGenerationLineAddin.csproj" (3) on node 1 (default targets).
C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AirCraftRouteGenerationLineAddin\AirCraftRouteGenerationLineAddin\AirCraftRouteGenerationLineAddin.csproj(150,5): error : The Esri WPF SDK is not correctly installed - 'ESRI.ArcGIS.OperationsDashboard.targets' not found (IDEIntegrationFolder='').
Done Building Project "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AirCraftRouteGenerationLineAddin\AirCraftRouteGenerationLineAddin\AirCraftRouteGenerationLineAddin.csproj" (default targets) -- FAILED.
Project "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\AllSolutionsWidgets\AllSolutionsWidgets.sln" (1) is building "C:\Program Files (x86)\Jenkins\workspace\Daily Build- solutions-widgets-wpf\source\BombThreatAddin\BombThreatAddin\BombThreatAddin.csproj" (4) on node 1 (default targets).
ResolveAssemblyReferences:
  Primary reference "ESRI.ArcGIS.Client".

**Comment by csmoore** [comment]
Just a reminder/addition to this discussion:

Unfortunately the version numbers are hard-coded in the .vsproj files (that use REGKEY lookups to find dependencies) - [Example](https://github.com/Esri/solutions-widgets-wpf/blob/master/source/AirCraftRouteGenerationLineAddin/AirCraftRouteGenerationLineAddin/AirCraftRouteGenerationLineAddin.csproj#L41)

So to fix this issue (and any issue really where we want to build against the current and next version) we want to have 2 branches that work with the **current** and **next version** of the product:

* Current Version (Currently 10.2.3 update 2?) – goes in **master branch**
* Next Version (Currently 10.3?) – in **“v.next” branch**

**Comment by csmoore** [comment]
@ACueva - is this something you feel comfortable fixing (Visual Studio settings?) or should @jrweakland assign to someone else?

**Comment by csmoore** [comment]
This should get fixed with #23
