### ISSUE TITLE
Bomb Threat tool config cog doesn't appear initially in Map tools list

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/solutions-widgets-wpf#30]
I created a simple Dashboard with a web map, and no data sources turned on, then added the Bomb Threat tool.

The tool appears in the list, but no config cog next to it.

Once I used a dashboard with some other widgets loaded, and data sources turned on, I could see the settings cog next to the tool. 

After this I always see the settings cog, even if I go back to a simple dashboard with no data sources.

**Comment by jofraley** [comment]
@jrweakland I am unable to reproduce this bug on multiple machines and even tried on a machine that  has never had dashboard installed on it before.  So am at a lose as to how to try to fix this if cannot recreate.

**Comment by joebayles** [comment]
@kerryrobinson can you reproduce this bug?

**Comment by kerryrobinson** [comment]
I had a hard time consistently reproducing this before.  I'll give it a go again to see if i can come up with a consistent case.

**Comment by joebayles** [comment]
OK... if you can consistently reproduce it, let's re-open and figure it out.

Otherwise, I'd agree this is closed.
