### ISSUE TITLE
Widgets need uploading to NSEC Portal

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-widgets-wpf#31]
I tried uploading these widgets to the NSEC portal and ran into build errors in Visual Studio. They need to be uploaded for testing against the latest version, for #23 and #28 to be closed.

- [x] Bomb Threat Addin
- [x] Buffer Map Tool
- [x] ERG Chemical AddIn
- [x] Farthest On Circle Addin
- [x] Find Closest Resource
- [ ] Order of Battle Addin
- [x] Range Fan Addin

**Comment by joebayles** [comment]
Once https://github.com/Esri/solutions-widgets-wpf/pull/32 is merged, I can do this.

**Comment by joebayles** [comment]
Running into the same issue @jofraley did on the portal... insufficient privileges. Release team is going to fix it and I will continue.

**Comment by joebayles** [comment]
@jofraley @ACueva set my permissions and it worked fine. Just so you know.

All the widgets are uploaded to NSEC save Order of Battle. @pHill5136 if you want to knock that out, that'd be great.

**Comment by ACueva** [comment]
Issue logged pertaining to portal permissions.
https://github.com/Esri/ops-server-config/issues/734

**Comment by jofraley** [comment]
@joebayles Yes, it can be closed

**Comment by joebayles** [comment]
@pHill5136 were you ever able to upload Order of Battle to the portal?

**Comment by joebayles** [comment]
Closing per @jofraley
